### ISSUE TITLE
Keyboard Management

### ISSUE THREAD

**Issue by mikekloster** [iwelabs/ILPDFKit#1]
This is very cool software! Thanks for making it open source.

I have been evaluating it for only an hour. Is there keyboard management to avoid text fields on the bottom of the view controller from being covered by the keyboard?

Along the same lines, re-centering the view if a selected field is covered by the keyboard would also be a great enhancement.

I'll try to dig in further to see if these are enhancements I can code up and submit as pull requests.

Great work! I already love this project.

**Comment by SaurabhPrajapati** [comment]
Still the textfields on lower side of Page are hide behind the keyboard  in small Example
