### ISSUE TITLE
Adobe Acrobat cannot read many of the files created

### ISSUE THREAD

**Issue by jbrx107** [iwelabs/ILPDFKit#16]
After filling in some forms, I see this error in Adobe Acrobat when opening the PDF files:

"There was an error opening this document.  The root object is missing or invalid."

Here is a link to a PDF form from around the Internet that do not work with ILPDFKit that show the above error:

http://www.stuart-design.co.uk/docs/Sample%20Fillable%20PDF%20Form.pdf

Here is another form that after I save it, I can view it in Preview but NOT in Adobe Acrobat:

http://www.thewebjockeys.com/TheWebJockeys/Fillable_PDF_Sample_from_TheWebJockeys_vC5.pdf

These are the very first two files that I tried - and neither of them currently works.  Any idea what the issue might be?

Thanks!

**Comment by derekblair** [comment]
I will add this shortly. In general, only 1.3 and before is supported for saving.
