### ISSUE TITLE
Installation problems with cocoapods

### ISSUE THREAD

**Issue by Biclops** [iwelabs/ILPDFKit#19]
Pod spec

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '7.0'
    xcodeproj 'Test.xcodeproj'
    pod 'ILPDFKit', '0.0.6'

If you open up the ILPDFKit folder while it's installing, you'll see the code downloading as it should but at the last phase it'll delete all the source files. 

I have no idea why it'd do that. 

Here's the terminal printout
dtmac:trunk dt$ pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Resolving dependencies of `Podfile`
Resolving dependencies for target `Pods' (iOS 7.0)
  - ILPDFKit (= 0.0.6)

Comparing resolved specification to the sandbox manifest
  A ILPDFKit

Downloading dependencies

-> Installing ILPDFKit (0.0.6)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/iwelabs/ILPDFKit.git /Users/dtan/Projects/BMS/trunk/Pods/ILPDFKit --single-branch --depth 1 --branch 0.0.6
     Cloning into '/Users/dt/Projects/test/trunk/Pods/ILPDFKit'...
     Note: checking out 'c2590b9db8d81c1c26887b0d126119428dd77f5d'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b new_branch_name
     

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-ILPDFKit` iOS 7.0
    - Installing target `Pods` iOS 7.0
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods` (`test.xcodeproj` project)

**Comment by derekblair** [comment]
Fixed

**Comment by Alkandros** [comment]
why this error happens?
