### ISSUE TITLE
Rendering of Form Fields are off on Multiple Pages

### ISSUE THREAD

**Issue by pprieur79** [iwelabs/ILPDFKit#20]
Not sure if this library is still being developed/supported but I just noticed that when you render a PDF form with text boxes on multiple pages the boxes seems to be offset.  For example on the first page everything is 100% perfect.  However the second page the boxes are all slightly offset, third page even more so, etc.  My guess is that the way it calculates the y margin might be a bit off as you add more pages.  just curious if anyone has run into this issue.  I'm on IOS 8 so not sure if it was an issue with previous versions (iPad/iPad mini/iPhone same issue).  I'm trying to narrow down problem and will post if I figure anything out

**Comment by flooie** [comment]
me as well

**Comment by derekblair** [comment]
Yes this is known issue. The solution I am moving toward is to render the PDF using a Quartz based view instead of UIWebView. This will allow for more precise control and accuracy of margins.

**Comment by Vortec4800** [comment]
I was able to partially fix this in the latest version on Cocoapods. It will probably still fall apart on very long documents, but if you only have a few pages the results are reasonably good.

It seems that the page margin is a little higher on pages 2 and on than it is on the first page. This means if you line up the Y margin on the first page, each page thereafter will be incorrect. I was able to fix this by subtracting a few pixels from the pageMargin in the loop for multiple pages: `pageOffset+= iheight*ifactor+ymargin-2.9;`

The other issue seems to be from converting the frame values to Integers, which loses a small amount of precision each time. By removing these conversions, the fields are slightly less uniform (as now they may be drawing on subpixels) but their positioning is more accurate as the fields go down the page.
`_pageFrame =  CGRectMake(correctedFrame.origin.x*factor+hmargin, correctedFrame.origin.y*factor+ymargin, correctedFrame.size.width*factor, correctedFrame.size.height*factor);` and `_uiBaseFrame = CGRectMake(_pageFrame.origin.x, _pageFrame.origin.y+pageOffset, _pageFrame.size.width, _pageFrame.size.height);`

These changes were made in the `createWidgetAnnotationViewForSuperviewWithWidth: xMargin: yMargin:` method in the `PDFForm` class. The full modified version of this method is here:

```objc
- (PDFWidgetAnnotationView *)createWidgetAnnotationViewForSuperviewWithWidth:(CGFloat)vwidth xMargin:(CGFloat)xmargin yMargin:(CGFloat)ymargin {
    if ((_annotFlags & PDFAnnotationFlagHidden) > 0) return nil;
    if ((_annotFlags & PDFAnnotationFlagInvisible) > 0) return nil;
    if ((_annotFlags & PDFAnnotationFlagNoView) > 0) return nil;
    CGFloat width = _cropBox.size.width;
    CGFloat maxWidth = width;
    for (PDFPage *pg in self.parent.document.pages) {
        if([pg cropBox].size.width > maxWidth) maxWidth = [pg cropBox].size.width;
    }
    /*
     vwidth-2*xmargin = pixel width of canvas on screen for full screen scaled page
     xmargin = pixel width of grey border between canvas and edge of UIWebView for full scaled page.
     maxWidth = PDF canvas points of widest page;
     ((vwidth-2*xmargin)/maxWidth) = converstion factor from canvas space to device space.
     Thus hmargin is the horizonal pixel margin from the border of the screen to the beginning of the page canvas.
     */
    CGFloat hmargin = ((maxWidth-width)/2)*((vwidth-2*xmargin)/maxWidth)+xmargin;
    CGFloat height = _cropBox.size.height;
    CGRect correctedFrame = CGRectMake(_frame.origin.x-_cropBox.origin.x, height-_frame.origin.y-_frame.size.height-_cropBox.origin.y, _frame.size.width, _frame.size.height);
    CGFloat realWidth = vwidth-2*hmargin;
    CGFloat factor = realWidth/width;
    CGFloat pageOffset = 0;
    for (NSUInteger c = 0; c < self.page-1; c++) {
        PDFPage *pg = self.parent.document.pages[c];
        CGFloat iwidth = [pg cropBox].size.width;
        CGFloat ihmargin = ((maxWidth-iwidth)/2)*((vwidth-2*xmargin)/maxWidth)+xmargin;
        CGFloat iheight = [pg cropBox].size.height;
        CGFloat irealWidth = vwidth-2*ihmargin;
        CGFloat ifactor = irealWidth/iwidth;
        pageOffset+= iheight*ifactor+ymargin-2.9;
    }
    _pageFrame =  CGRectMake(correctedFrame.origin.x*factor+hmargin, correctedFrame.origin.y*factor+ymargin, correctedFrame.size.width*factor, correctedFrame.size.height*factor);
    if (_formUIElement) {
        _formUIElement = nil;
    }
    _uiBaseFrame = CGRectMake(_pageFrame.origin.x, _pageFrame.origin.y+pageOffset, _pageFrame.size.width, _pageFrame.size.height);
    switch (_formType) {
        case PDFFormTypeText:
            _formUIElement = [[PDFFormTextField alloc] initWithFrame:_uiBaseFrame multiline:((_flags & PDFFormFlagTextFieldMultiline) > 0) alignment:_textAlignment secureEntry:((_flags & PDFFormFlagTextFieldPassword) > 0) readOnly:((_flags & PDFFormFlagReadOnly) > 0)];
        break;
        case PDFFormTypeButton: {
            BOOL radio = ((_flags & PDFFormFlagButtonRadio) > 0);
            if (_setAppearanceStream) {
                if ([_setAppearanceStream rangeOfString:@"ZaDb"].location != NSNotFound && [_setAppearanceStream rangeOfString:@"(l)"].location!=NSNotFound)radio = YES;
            }
            PDFFormButtonField *temp = [[PDFFormButtonField alloc] initWithFrame:_uiBaseFrame radio:radio];
            temp.noOff = ((_flags & PDFFormFlagButtonNoToggleToOff) > 0);
            temp.name = self.name;
            temp.pushButton = ((_flags & PDFFormFlagButtonPushButton) > 0);
            temp.exportValue = self.exportValue;
            _formUIElement = temp;
        }
        break;
        case PDFFormTypeChoice:
            _formUIElement = [[PDFFormChoiceField alloc] initWithFrame:_uiBaseFrame options:_options];
        break;
        case PDFFormTypeSignature:
            _formUIElement = [[PDFFormSignatureField alloc] initWithFrame:_uiBaseFrame];
        break;
        case PDFFormTypeNone:
        default:
            break;
    }
    if (_formUIElement) {
        [_formUIElement setValue:self.value];
        _formUIElement.delegate = self;
        [self addObserver:_formUIElement forKeyPath:@"value" options:NSKeyValueObservingOptionNew context:NULL];
        [self addObserver:_formUIElement forKeyPath:@"options" options:NSKeyValueObservingOptionNew context:NULL];
    }
    return _formUIElement;
}
```

This is essentially a hack until more precise rendering using Quartz methods causes this to be unnecessary. But, it may be helpful for someone else who wants to use this framework in its current state with a PDF that has a few pages in it.
