### ISSUE TITLE
Saving partially flattened data

### ISSUE THREAD

**Issue by magmatic** [iwelabs/ILPDFKit#21]
I would like to save the PDF document in such a way that the form elements are flattened, but interactive URLs remain clickable. Can you give any info as to how to modify `flattenedData:` method to achieve that? I looked over the class reference and can't seem to see anything that relates to clickable links.

**Comment by derekblair** [comment]
This unfortunately hard to do but is part of of the things I am working on. Keep your eyes open for future releases.
